// src/components/modals/shares.jsx
export function SharesModal() {
    const openSharesModal = () => {
        return
    }

    const sharesModalEnter = () => {
        return
    }

    return (
        <div className='hidden fixed z-10 left-0 top-0 w-full h-full overflow-auto bg-opacity-40 bg-black modal' id='shares-modal' onClick={ openSharesModal }>
            <div className='absolute bg-blueGray-light inset-0 m-auto p-8 w-96 h-40 text-center'>
                <span className='text-white'>Write the number of shares</span>
                <input type="number" max={1000} min={2} defaultValue={2} pattern={'d'} className='invalid:bg-red-200 m-2' id='layer-count'></input><br />
                <span className='text-xs text-red-200'>min=2 max=1000</span><br />
                <button className='hover:bg-blueGray-medium-light active:bg-blueGray-medium-dark p-1 text-white' onClick={ sharesModalEnter }>Enter</button>
            </div>
        </div>
    )
}

// src/components/encryption/Shares.svelte
<div class='flex flex-col h-1/3 bg-blueGray-light'>
  <span class='flex-none pl-2 pointer-events-none text-white'>
    Shares
  </span>
  <div class='flex-auto'>
    <!-- start inner overflow item -->
    <div class="relative w-full h-full bg-blueGray-medium-light">
      <div class='absolute inset-0 overflow-auto'>
        <div class='ml-1 grid grid-cols-10 place-content-start gap-1'>
                <!-- images -->
        </div>
      </div>
    </div>
    <!-- end inner overflow item -->
  </div>
  <div class='flex h-7 items-center'>
    <button class='mx-1 bg-blueGray-light hover:bg-blueGray-medium-light active:bg-blueGray-medium-dark px-2'>
      <span class='text-white text-sm'>Add</span>
    </button>
    <button class='mx-1 bg-blueGray-light hover:bg-blueGray-medium-light active:bg-blueGray-medium-dark px-2'>
      <span class='text-white text-sm'>Remove</span>
    </button>
  </div>
</div>
